[package]
name = "ft-dispatch"
version = "0.1.0"
edition = "2024"

[dependencies]
ft-core = { workspace = true }
ft-kernel-cpu = { workspace = true }

[dev-dependencies]
proptest = "1.6.0"

[lints]
workspace = true
